# Aggregations: Min, Max, and Everything In Between

Numpy has fast built-in aggregation functions for working on arrays; we'll discuss and demonstrate some of them here

## Summing the Values in an Array

As as quick example, consider computing the sum of all values in an array. Python itself can do this using the buil-in `sum` function:

In [2]:
import numpy as np

In [3]:
L = np.random.random(100)

In [4]:
sum(L)

52.26043277604201

In [5]:
np.sum(L)

52.260432776042

NumPy version of the operation is computed much more quickly:

In [6]:
big_array = np.random.rand(1_000_000)

In [7]:
%timeit sum(big_array)
%timeit np.sum(big_array)

179 ms ± 18.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.18 ms ± 120 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Minimun and Maximum

In [8]:
min(big_array), max(big_array)

(6.990105299031768e-07, 0.9999992162584009)

In [9]:
%timeit min(big_array)
%timeit np.min(big_array)

84.3 ms ± 2.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
471 µs ± 23.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


For `min` and `max` and `sum`, and seveal other NumPy aggregates a shorter syntax is to use methods ofthe array object itself:

In [10]:
print(big_array.min(), big_array.max(), big_array.sum())

6.990105299031768e-07 0.9999992162584009 499848.77304655063


## Multi dimensional aggregates

One common type of aggregation operation is an aggregate along a row or column.
Say you have some data stored in a two-dimensional array:

In [11]:
M = np.random.random((3, 4))
print(M)

[[0.17768175 0.26264154 0.63198318 0.50042224]
 [0.52442396 0.5038188  0.56468719 0.29566009]
 [0.37235568 0.10338796 0.66210778 0.00653843]]


By default, each NumPy aggregation function will return the aggregate over the entire array:

M.sum()

Aggregation functions take an additional argument specifying the axis along which the aggregate is computed. 
For example, we can find the minimum value within each column by specifying `axis=0`.

In [12]:
M.min(axis=0)

array([0.17768175, 0.10338796, 0.56468719, 0.00653843])

In [13]:
M.max(axis=1)

array([0.63198318, 0.56468719, 0.66210778])

The `axis` keyword specifies the dimension of hte arrya that will be collapsed. So specigying `axis=0` means that the first axis will be collapsed. For two-dimensional arrays, this means that values within each column will be aggregated.

## Other aggregations functions

Most aggregates have a `NaN` safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point `NaN` value.


```
Function Name 	NaN-safe Version 	Description
np.sum 	np.nansum 	Compute sum of elements
np.prod 	np.nanprod 	Compute product of elements
np.mean 	np.nanmean 	Compute mean of elements
np.std 	np.nanstd 	Compute standard deviation
np.var 	np.nanvar 	Compute variance
np.min 	np.nanmin 	Find minimum value
np.max 	np.nanmax 	Find maximum value
np.argmin 	np.nanargmin 	Find index of minimum value
np.argmax 	np.nanargmax 	Find index of maximum value
np.median 	np.nanmedian 	Compute median of elements
np.percentile 	np.nanpercentile 	Compute rank-based statistics of elements
np.any 	N/A 	Evaluate whether any elements are true
np.all 	N/A 	Evaluate whether all elements are true
```
