# The basics of numpy arrays

This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reashape, and join the arrays.

We'll cover:

- Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays.
- Indexing of arrays: Getting and setting the value of individual array elements.
- Slicing of arrays: Getting and setting smaller subarrays withing a larger array.
- Reshaping of arrays: Changing the shape of a fiven array.
- Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

##  NumPy Array Attributes

In [146]:
import numpy as np

### Setting the seed

In [147]:
import numpy as np 
np.random.seed(0)

In [148]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4 ,5))

### Each array has `ndim`(number of dimentions), `shape`(the size of each dimension),  `size`(total size of the array)

In [149]:
print(f'x3 ndim: {x3.ndim}')
print(f'x3 shape {x3.shape}')
print(f'x3 size: {x3.size}')

x3 ndim: 3
x3 shape (3, 4, 5)
x3 size: 60


In [150]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [151]:
print("dtype: ", x3.dtype)

dtype:  int32


Other atrributes include `itemsize`, which lists the size(in bytes) of each array element, and `nbytes`, which lists the total size (in bytes) of the array:

In [152]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes: 240 bytes


## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel wuite familiar. In a one-dimensional array, the ith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python list:

In [153]:
x1

array([5, 0, 3, 3, 7, 9])

In [154]:
x1[0]

5

In [155]:
x1[4]

7

To index from the end of the array, you can use negative indices:


In [156]:
x1[-1]

9

In [157]:

x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:


In [158]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [159]:

x2[0, 0]

3

In [160]:
x2[2, 0]

1

In [161]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [162]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integerarray, the value will be silently truncated. Don't be cauth unaware by this behavior!

In [163]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon `:` character. The NumPy slicing syntax follows that of the standard Python list: to access a slice of an array `x`, use this:

In [164]:
x = np.arange(10)

In [165]:
x[:5] # first 5 elements

array([0, 1, 2, 3, 4])

In [166]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [167]:
x[4:7] # middle subarray

array([4, 5, 6])

In [168]:
x[::2] # every even element

array([0, 2, 4, 6, 8])

In [169]:
x[1::2] # every odd element

array([1, 3, 5, 7, 9])

A potentially confusing case is when the `step` value is negative. In this case, the defaults for `starts` and `stop` are swapped. This becomes a convenient way to reverse an array:


In [170]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [171]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

## Multi dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas, For example:

In [172]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [173]:
x2[:2, :3] # two first rows and 3 first columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [174]:
x2[:3, ::2] # three first rows and columns 0 and 2, be careful because python index start in 0

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [175]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### Accessing array rows and columns

ONe commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon

In [176]:
print(x2[:, 0]) # all rows, first column

[12  7  1]


In [177]:
print(x2[0, :]) # first row

[12  5  2  4]


In this case of row access, the empty slice can be omitted for a more compact syntax:

In [178]:
print(x2[0]) # first row, this is equivalent to x[0, :]

[12  5  2  4]


## Subarrays as no-copy views

One important-and extremely useful-thin to know about arrays slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [179]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Extract 2x2 subarray from this

In [180]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


### If we modify this subarray, the original array is changed, BE CAREFULL WITH THIS. This is useful too, that means that we work with large datasets,
we can access and process pieces of these datasets without the need to copy the underlying data buffer.

In [181]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [182]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This

## Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be 
most easily done with the `copy()` method:

In [183]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [184]:
x2_sub_copy[0, 0] = 42

In [185]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operatio nis reshaping of arrays. The most flexible way of doing this is with the `reshape` method. For example, if
you want to put the numbers 1 throught 9 in a 3x3 grid, you can do the following:

In [186]:
grid = np.arange(1, 10)
grid = grid.reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### The size of initial array must match the size of the reshaped array. There possible, the `reshape` will use a no-copy view.
### Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix
### This can be done with reshape or with newaxis keyword within a slice opeartion

In [187]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [188]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [189]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [190]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and
to conversely split a single array into multiple arrays. We'll take a look at those operations here.

## Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`.

###  `np.concatenate` takes a tuple or list of arrays as its first argument, as we can see here:

In [191]:
x = np.arange(1, 5)
y  = np.arange(5, 10)

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### You can concatenate more than two arrays at once:

In [192]:
z = np.arange(10, 12)

In [193]:
np.concatenate([x, y , z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Using with two dimensional arrays:

In [194]:
grid = np.array([[1, 2 ,3], [4 , 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [196]:
# concatenate along the second axis(zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### you can use concatenate mixing 1D and 2D arrays you have to do the reshape first

In [197]:
t = np.arange(0,3)
t = t.reshape(1,3)
t
np.concatenate([grid, t])

t[0, 2]

2

### Our use `np.vstack` (vertical stack, axis=0, add rows) or `np.hstack` (horizontal stack, axis=1, add columns), `np.dstack` will stack arrays along the third axis

In [198]:
x = np.array([1 ,2 ,3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [199]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])                

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of arrays

The opposite of concatenation nis splitting, which is implemented by the functions `np.split`, `np.hspli`, `np.vsplit`. 
For each of these, we can pass a list of indices giving the split points:

In [200]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that N splits-points, leads to N + 1 subarrays. The related functions `np.hsplit` and `np.vsplit` are similar:

In [201]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [212]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [209]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
