# Understanding Data types in Python

In [1]:
import numpy as np

## Creating Arrays from Python lists

NumPy is constrained to arrays that all contain the same type. If types do not match, Numpy will upcast if possible(for example form int to float)

In [2]:
# integer array:

np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([1, 43, 4.5 , 6.4])

array([ 1. , 43. ,  4.5,  6.4])

### Set the data type explicity

In [5]:
np.array([1, 3, 4 ,5], dtype='float32')

array([1., 3., 4., 5.], dtype=float32)

### Multi-dimensional arrays

In [7]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4 ,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating arrays from Scratch

### Create a length-10 integer array fileld with zeros

In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Create a 3x5 floating-point array filled with ones

In [10]:
np.ones((3, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Create a 3x5 array filled with specific value

In [11]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

### Create a arra y filled with a linear sequence starting at 0, ending at 20, stepping by 2

In [13]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Create an array of five values evenly spaced between 0 and 1

np.linspace(0, 1 , 5)

### Create a 3x3 array of uniformly distributed random values between 0 and 1

In [23]:
np.random.random((3,3))

array([[0.62467854, 0.9457966 , 0.1839315 ],
       [0.98841515, 0.00908106, 0.59269052],
       [0.01618051, 0.63825626, 0.90363935]])

### create a 3x3 identity matrix

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create an uninitialized array of three integers, the values will be whatever happens to already exist at that memory location

In [33]:
np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types
NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to user of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table. Note that when constructing an array, they can be specified using a tring: