# Computation on NumPy Arrays: Universal Functions

The reasons that NumPy is so improtant in the Python data science, computation on NumPy arrays can be very fast, or it cant be very slow. The key to making it fast
is to use vectorized operations, generally implemented through NumPy's universal functions(ufuncs).

This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient.

## The Slowness of Loops

Python's default implementation (known as CPython) foes some operatiosn very slowly.



In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [7]:
big_array = np.random.randint(1, 100, size=1_000_000)
%timeit compute_reciprocals(big_array)

2.12 s ± 107 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Even cells phones have processing speeds measured in Giga-FLOPS, this seem almost absurdly slow. The bottleneck here is no the operation
but the typecheking and function dispatches taht CPython must do at each cycle of the loop.

Python first examines the object's type and does dynamic lookup of the correct function to use for that type. If we were working in 
compiled code instead, this type specification would be known before the code executes and the result could be computed much more efficiently.

## Introducing UFuncs

For many types of operations, NumPy provides a convenient interface into just his kind of statically typed, compiled routine. This is known as a vectorized operation. This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.

In [ ]:
print(compute_reciprocals((values)))
print(1.0 / values)

In [ ]:
%timeit (1.0 / big_array)

Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated oepratiosn on values in NumPy arrays. Ufuncs are extremely flexible - before we saw an opeartion between a scalar and an array, but we can also operate between two arrays:

In [11]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

And ufunc operations are not limited to be one-dimensional arrays-they can also act on multi-dimensional arrays as well:

In [12]:
x = np.arange(9).reshape(3,3)
3 ** x

array([[   1,    3,    9],
       [  27,   81,  243],
       [ 729, 2187, 6561]], dtype=int32)

computations using vectorization through ufuncs are nearly always more efficient
than their conterpart implemented using Python loops.

Any time you see such a loop in a Python script, you should consider whether it can be
replaced with a vectorized expression